SELECT * FROM TB_INTRA_BOARD_MST;
SELECT * FROM TB_INTRA_CP_INFO; --회사정보테이블의 회사 정보 seq 
SELECT * FROM TB_INTRA_BOARD_INFO;	
SELECT SEQ_TB_INTRA_BOARD_MST_PK.CURRVAL FROM TB_INTRA_BOARD_MST;
 DELETE FROM TB_INTRA_BOARD_MST WHERE MST_SEQ = 5;
SELECT CP_INFO_SEQ FROM TB_INTRA_CP_INFO; --회사정보테이블의 회사 정보 seq 
SELECT SEQ_TB_INTRA_BOARD_MST_PK.CURRVAL FROM DUAL;
ALTER TABLE TB_INTRA_BOARD_INFO MODIFY DEL_YN NULL; --임시로 NULL 
ROLLBACK;
--게시판 정보 마스터 
INSERT INTO TB_INTRA_BOARD_MST VALUES(SEQ_TB_INTRA_BOARD_MST_PK.NEXTVAL, 1, 'N', '공지사항 T', '나세영T','2022-02-17','',''); -- 게시판 정보 마스터 
INSERT INTO TB_INTRA_BOARD_MST VALUES(SEQ_TB_INTRA_BOARD_MST_PK.NEXTVAL, 1, 'N', '사내소식 T', '나세영T','2022-02-17','','');
INSERT INTO TB_INTRA_BOARD_MST VALUES(SEQ_TB_INTRA_BOARD_MST_PK.NEXTVAL, 1, 'N', '자유게시판 T', '나세영T','2022-02-18','','');
INSERT INTO TB_INTRA_BOARD_MST VALUES(SEQ_TB_INTRA_BOARD_MST_PK.CURRVAL, 2, 'N', '공지사항T', '양은솔T','2022-02-17','','');
--회사 정보
INSERT INTO TB_INTRA_CP_INFO VALUES(SEQ_TB_INTRA_CP_INFO_PK.CURRVAL,'이젠솔루션','08:53','18:08','','','','','','');
INSERT INTO TB_INTRA_CP_INFO VALUES(SEQ_TB_INTRA_CP_INFO_PK.NEXTVAL,'해피솔루션','08:27','17:27','','','','','','');

--게시판 정보
--                                                           게시판 SEQ. 마스터 SEQ. 회사정보 SEQ. 등록자 ID, 등록일, 수정자, 수정일, 삭제유무, 조회수, 추천수, 제목, 내용, 게시판구분 
INSERT INTO TB_INTRA_BOARD_INFO VALUES(SEQ_TB_INTRA_BOARD_INFO_PK.NEXTVAL,1,1,'NA01','2022-02-17','','','N',1 ,1 ,'2월 공지사항','2월 공지','ABC1');
INSERT INTO TB_INTRA_BOARD_INFO VALUES(SEQ_TB_INTRA_BOARD_INFO_PK.NEXTVAL,1,1,'NA01','2022-03-02','','','N',1 ,1 ,'3월 공지사항','3월 공지','ABC2');
INSERT INTO TB_INTRA_BOARD_INFO VALUES(SEQ_TB_INTRA_BOARD_INFO_PK.NEXTVAL,2,1,'NA01','2022-03-02','','','N',1 ,1 ,'3월 사내소식','사내소식 내용','ABC3');
INSERT INTO TB_INTRA_BOARD_INFO VALUES(SEQ_TB_INTRA_BOARD_INFO_PK.NEXTVAL,3,1,'NA01','2022-03-21','','','N',1 ,1 ,'자유게시판 제목 TEST','자유게시판 내용','ABC4');
INSERT INTO TB_INTRA_BOARD_INFO VALUES(SEQ_TB_INTRA_BOARD_INFO_PK.NEXTVAL,4,2,'YANG01','2022-03-04','','','N',1 ,1 ,'3월 공지사항','3월 공지','ABC5');
INSERT INTO TB_INTRA_BOARD_INFO VALUES(SEQ_TB_INTRA_BOARD_INFO_PK.NEXTVAL,4,2,'YANG01','2022-04-05','','','N',1 ,1 ,'4월 공지사항','4월 공지','ABC6');


ALTER SEQUENCE SEQ_TB_INTRA_CP_INFO_PK INCREMENT BY -1; 
SELECT SEQ_TB_INTRA_BOARD_MST_PK.CURRVAL FROM DUAL;
ALTER SEQUENCE SEQ_TB_INTRA_BOARD_MST_PK INCREMENT BY 1; 
SELECT SEQ_TB_INTRA_CP_INFO_PK.CURRVAL FROM DUAL;
DROP SEQUENCE SEQ_TB_INTRA_BOARD_MST_PK
CREATE SEQUENCE SEQ_TB_INTRA_BOARD_MST_PK
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    CYCLE 
    CACHE 1000 ;
 CREATE SEQUENCE SEQ_TB_INTRA_BOARD_INFO_PK
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    CYCLE 
    CACHE 1000;
    CREATE SEQUENCE SEQ_TB_INTRA_CP_INFO_PK
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    CYCLE 
    CACHE 1000

INSERT INTO TB_INTRA_BOARD_INFO (BOARD_SEQ,MST_SEQ,CP_INFO_SEQ, TITLE,
USER_ID, REG_DT,DEL_YN, VIEW_CNT, TYPE_CD, RECOMEND_CNT, CONTENTS) VALUES 
	(SELECT NVL(MAX(BOARD_SEQ),0)+1 FROM TB_INTRA_BOARD_INFO),
	(SELECT NVL(MAX(MST_SEQ),0)+1 FROM TB_INTRA_BOARD_INFO),
		(SELECT NVL(MAX(CP_INFO_SEQ),0)+1 FROM TB_INTRA_BOARD_INFO),
	'안녕하세요제목', 'NA01', '2022-02-21','N', '1','abc', '1', '내용내용');




SELECT board_seq, title, user_id, reg_dt
FROM TB_INTRA_BOARD_INFO;

DELETE FROM TB_INTRA_BOARD_INFO WHERE BOARD_SEQ ='2024' 
SELECT BOARD_SEQ, MST_SEQ , CP_INFO_SEQ , TITLE, USER_ID, reg_Dt, CONTENTS
FROM TB_INTRA_BOARD_INFO
WHERE BOARD_SEQ = '17';
